# Generated by Django 5.1.1 on 2024-09-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('size', models.IntegerField(blank=True, default=1024, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
