# Generated by Django 5.1.1 on 2024-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('doors', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('luggage', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('a', 'Automatic'), ('m', 'Manual'), ('t', 'Triptonic')], max_length=10)),
                ('airConditioning', models.BooleanField()),
                ('age', models.PositiveIntegerField()),
                ('pricePerHour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuelType', models.CharField(choices=[('g', 'Gasoline'), ('d', 'Diesel'), ('e', 'Electricity'), ('h', 'Hybrid'), ('hy', 'Hydrogen'), ('l', 'LPG'), ('c', 'CNG')], max_length=2)),
                ('builtIn', models.BooleanField(default=True)),
                ('image', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
